SET GLOBAL time_zone = '-5:00';
USE control_personas;

DROP TABLE IF EXISTS TM_HISTORIAL;
DROP TABLE IF EXISTS TM_PERSONAS;
DROP TABLE IF EXISTS TR_TIPOS_IDENTIFICACION;
DROP TABLE IF EXISTS TP_ESTRUCTURAS_FISICAS;
DROP TABLE IF EXISTS TR_DEPARTAMENTOS;



CREATE TABLE IF NOT EXISTS TR_TIPOS_IDENTIFICACION
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    CODIGO VARCHAR(50) NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL
);

INSERT INTO TR_TIPOS_IDENTIFICACION
	(CODIGO, NOMBRE)
VALUES
	('CC', 'Cédula de ciudadania'),
    ('TI', 'Tarjeta de identidad'),
    ('CE', 'Cédula extrangera');

CREATE TABLE IF NOT EXISTS TM_PERSONAS
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NUMERO_IDENTIFICACION VARCHAR(100) NOT NULL,
    PRIMER_NOMBRE VARCHAR(50) NOT NULL,
    SEGUNDO_NOMBRE VARCHAR(50),
    PRIMER_APELLIDO VARCHAR(50),
    SEGUNDO_APELLIDO VARCHAR(50),
    FECHA_CREACION DATETIME DEFAULT NOW(),
    FECHA_ACTUALIZACION DATETIME DEFAULT NOW(),
    FECHA_NACIMIENTO DATETIME,
    EDAD INT,
    ID_TIPO_IDENTIFICACION INT,
    
    CONSTRAINT FK_PERSONAS_TIPOS_IDENTIFICACION
    FOREIGN KEY (ID_TIPO_IDENTIFICACION) REFERENCES TR_TIPOS_IDENTIFICACION(ID)
    ON UPDATE CASCADE
    ON DELETE SET NULL
    
);

CREATE TABLE IF NOT EXISTS TR_DEPARTAMENTOS
(
	ID INT PRIMARY KEY,
    DESCRIPCION VARCHAR(150) NOT NULL
);

INSERT INTO TR_DEPARTAMENTOS 
(ID, DESCRIPCION)
VALUES
	(5,'ANTIOQUIA'),
	(8,'ATLÁNTICO'),
	(11,'BOGOTÁ, D.C.'),
	(13,'BOLÍVAR'),
	(15,'BOYACÁ'),
	(17,'CALDAS'),
	(18,'CAQUETÁ'),
	(19,'CAUCA'),
	(20,'CESAR'),
	(23,'CÓRDOBA'),
	(25,'CUNDINAMARCA'),
	(27,'CHOCÓ'),
	(41,'HUILA'),
	(44,'LA GUAJIRA'),
	(47,'MAGDALENA'),
	(50,'META'),
	(52,'NARIÑO'),
	(54,'NORTE DE SANTANDER'),
	(63,'QUINDIO'),
	(66,'RISARALDA'),
	(68,'SANTANDER'),
	(70,'SUCRE'),
	(73,'TOLIMA'),
	(76,'VALLE DEL CAUCA'),
	(81,'ARAUCA'),
	(85,'CASANARE'),
	(86,'PUTUMAYO'),
	(88,'ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA'),
	(91,'AMAZONAS'),
	(94,'GUAINÍA'),
	(95,'GUAVIARE'),
	(97,'VAUPÉS'),
	(99,'VICHADA');

CREATE TABLE IF NOT EXISTS TP_ESTRUCTURAS_FISICAS
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(200),
    DIRECCION VARCHAR(200) NOT NULL,
    CIUDAD VARCHAR(200),
    FECHA_CREACION DATETIME DEFAULT NOW(),
    FECHA_ACTUALIZACION DATETIME DEFAULT NOW(),
    ID_DEPARTAMENTO INT,
    
    CONSTRAINT FK_ESTRUCRTURAS_FISICAS_DEPARTAMENTOS
    FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES TR_DEPARTAMENTOS(ID)
    ON UPDATE CASCADE
    ON DELETE SET NULL    
);


CREATE TABLE IF NOT EXISTS TM_HISTORIAL
(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	FECHA_INGRESO DATETIME DEFAULT NOW(),
	FECHA_SALIDA DATETIME DEFAULT NULL,
    FECHA_CREACION DATETIME DEFAULT NOW(),
    FECHA_ACTUALIZACION DATETIME DEFAULT NOW(),
    ID_ESTRUCTURA_FISICA INT NOT NULL,
    ID_PERSONA_INGRESA INT NOT NULL,    
    ID_PERSONA_REGISTRA INT NOT NULL,
    
    CONSTRAINT FK_HISTORIAL_ESTRUCTURA_FISICA 
    FOREIGN KEY (ID_ESTRUCTURA_FISICA) REFERENCES TP_ESTRUCTURAS_FISICAS(ID),
    
    CONSTRAINT FK_HISTORIAL_PERSONA_INGRESA
    FOREIGN KEY (ID_PERSONA_INGRESA) REFERENCES TM_PERSONAS(ID),    
    
    CONSTRAINT FK_HISTORIAL_PERSONA_REGISTRA
    FOREIGN KEY (ID_PERSONA_REGISTRA) REFERENCES TM_PERSONAS(ID)
);